### ISSUE TITLE
鉴权机制可能存在被绕过的风险

### ISSUE THREAD

**Issue by kallydev** [WetABQ/Nukkit-NPLKernel#1]
有幸看到这挺有意思的项目，在阅读所提供的文档后，我意识到该鉴权机制可能还有些不足之处。

具体思路是重写一个 NPLKernel，通过文档了解到三个 API 鉴权函数的返回值生成方式，其中最关键的就是 `checkKernel` 函数中 `原版 NPLKernel 类的 MD5`。若思路成立，只需要把 MD5 写入，就能计算出正确的返回值。

如果没有理解错，NPLKernel 的 `checkLicense` 函数通过 try 处理验证的结果，那么不触发 Exception 就能通过验证。最后，`checkLicenseStatus` 函数就只需要让 status 永远为 true 就能够欺骗插件。

因为闭源不方便进一步分析，我通过反推写下这些代码，也许能绕过该鉴权机制。

```java
package top.wetabq.nplkernel;

import org.apache.commons.codec.digest.Md5Crypt;

public class NPLKernel extends PluginBase {
	
	private static String privateKey;

	public static void checkLicense(int pluginId, int versionNum, String privateKey, String publicKey) {
		NPLKernel.privateKey = privateKey;
        }

	public static String checkLicenseStatus(int pluginId) {
		return Md5Crypt.md5Crypt((NPLKernel.privateKey + true).getBytes());
	}
	
	public static String checkKernel(int pluginId) {
		return Md5Crypt.md5Crypt((NPLKernel.privateKey + "原版 NPLKernel 的 MD5").getBytes());
	}
	
}
```

**Comment by WetABQ** [comment]
思路可以破解，但很难嵌入或重写NPLKernel这个类，修复思路暂时没有

**Comment by WetABQ** [comment]
大概想了一下，解决思路：更改SDK中检查kernel和授权的顺序，先检查kernel后检查授权，这样privateKey就不会被获取

**Comment by kallydev** [comment]
目前插件的设计思路想必是参考过 Nukkit 的 Plugin Manager，但这样设计很难保证 SDK 是原版。另外，SDK 的网络验证部分并没有起到实际作用，服务器仅提供了是否授权的结果，这在破解的过程中无关紧要。在 SDK 更新后，MD5 验证也将失效，建议往类似 RSA 的方向进行设计。

**Comment by WetABQ** [comment]
可以添加一下联系方式方便详谈吗？

**Comment by kallydev** [comment]
Telegram 可以么，我的用户名是 KallyDev

**Comment by WetABQ** [comment]
Completely Fixed
